/**
 * The document view of generated media: which generation placeholders a course
 * still carries, and how one of them is replaced by an allocated asset id.
 *
 * Pure and IO-free over the document, so both the write-back funnel and the
 * "has this already been generated?" test share one definition of where a
 * generated reference lives. Slots come from the DSL's own slot classification
 * (`slideMediaReferenceSlots`), so a new media-bearing property is picked up
 * here the moment the contract describes it.
 */
import type { Slide } from '@openmaic/dsl';

import { isGeneratedMediaPlaceholder } from '@/lib/media/media-ref';
import { slideMediaReferenceSlots } from '@/lib/media/slide-media-slots';
import type { Scene, Stage } from '@/lib/types/stage';

/** One generated placeholder and the allocated identities that replace it. */
export interface GeneratedMediaReferenceRewrite {
  /** The `gen_img_*` / `gen_vid_*` value the document holds today. */
  readonly placeholderRef: string;
  /** The id the asset pool allocated for the generated bytes. */
  readonly assetId: string;
  /** Allocated id for a generated video poster, when one was stored. */
  readonly posterAssetId?: string;
}

/** A course's slide-bearing surfaces, as much of them as a caller holds. */
export interface MediaBearingDocument {
  readonly stage?: Pick<Stage, 'whiteboard'> | null;
  readonly scenes?: readonly Scene[];
  /** The course has no outline still waiting for its scene. */
  readonly generationComplete?: boolean;
}

type SlideLike = Pick<Slide, 'background' | 'elements'>;

function slidesOfScene(scene: Scene): SlideLike[] {
  const slides: SlideLike[] = [];
  if (scene.content?.type === 'slide') slides.push(scene.content.canvas);
  for (const whiteboard of scene.whiteboards ?? []) slides.push(whiteboard);
  return slides;
}

/**
 * Replace every occurrence of one placeholder in a slide, in place.
 *
 * A generated video repeats its reference across `src` and `mediaRef`, so all
 * matching slots move together. The poster is written only onto an element
 * this rewrite actually matched, and only when that element has no poster of
 * its own yet — an author-chosen poster is never overwritten by a generated
 * one.
 */
export function rewriteSlideMediaReference(
  slide: SlideLike,
  rewrite: GeneratedMediaReferenceRewrite,
): boolean {
  const slots = [...slideMediaReferenceSlots(slide)];
  const matchedElements = new Set<number>();
  let changed = false;

  for (const slot of slots) {
    if (slot.read() !== rewrite.placeholderRef) continue;
    slot.write(rewrite.assetId);
    changed = true;
    if (slot.elementIndex !== undefined) matchedElements.add(slot.elementIndex);
  }

  if (rewrite.posterAssetId) {
    for (const slot of slots) {
      if (slot.kind !== 'video-poster') continue;
      if (slot.elementIndex === undefined || !matchedElements.has(slot.elementIndex)) continue;
      const current = slot.read();
      if (current && !isGeneratedMediaPlaceholder(current)) continue;
      slot.write(rewrite.posterAssetId);
      changed = true;
    }
  }

  return changed;
}

/** Apply a rewrite to a scene's canvas and whiteboards, in place. */
export function rewriteSceneMediaReference(
  scene: Scene,
  rewrite: GeneratedMediaReferenceRewrite,
): boolean {
  let changed = false;
  for (const slide of slidesOfScene(scene)) {
    if (rewriteSlideMediaReference(slide, rewrite)) changed = true;
  }
  return changed;
}

/** Apply a rewrite to the stage-level whiteboard slides, in place. */
export function rewriteStageMediaReference(
  stage: Pick<Stage, 'whiteboard'> | null | undefined,
  rewrite: GeneratedMediaReferenceRewrite,
): boolean {
  let changed = false;
  for (const slide of stage?.whiteboard ?? []) {
    if (rewriteSlideMediaReference(slide, rewrite)) changed = true;
  }
  return changed;
}

/** Every generation placeholder a scene currently carries. */
export function sceneMediaPlaceholders(scene: Scene): Set<string> {
  const refs = new Set<string>();
  for (const slide of slidesOfScene(scene)) {
    for (const slot of slideMediaReferenceSlots(slide)) {
      const ref = slot.read();
      if (ref && isGeneratedMediaPlaceholder(ref)) refs.add(ref);
    }
  }
  return refs;
}

/** Every generation placeholder the stage whiteboard currently carries. */
export function stageMediaPlaceholders(
  stage: Pick<Stage, 'whiteboard'> | null | undefined,
): Set<string> {
  const refs = new Set<string>();
  for (const slide of stage?.whiteboard ?? []) {
    for (const slot of slideMediaReferenceSlots(slide)) {
      const ref = slot.read();
      if (ref && isGeneratedMediaPlaceholder(ref)) refs.add(ref);
    }
  }
  return refs;
}

/** Whether a scene still holds this placeholder in any of its media slots. */
export function sceneCarriesMediaReference(scene: Scene, placeholderRef: string): boolean {
  return slidesOfScene(scene).some((slide) =>
    [...slideMediaReferenceSlots(slide)].some((slot) => slot.read() === placeholderRef),
  );
}

/** Whether the stage whiteboard still holds this placeholder. */
export function stageCarriesMediaReference(
  stage: Pick<Stage, 'whiteboard'> | null | undefined,
  placeholderRef: string,
): boolean {
  return (stage?.whiteboard ?? []).some((slide) =>
    [...slideMediaReferenceSlots(slide)].some((slot) => slot.read() === placeholderRef),
  );
}

/**
 * What the document says about generated media, as the facts the skip test
 * needs.
 */
export interface GeneratedMediaDocumentIndex {
  /** Orders of the scenes that exist today. */
  readonly materializedOrders: ReadonlySet<number>;
  /** Every generation placeholder the document still carries. */
  readonly pendingPlaceholders: ReadonlySet<string>;
  /** Whether every outline of this course already has its scene. */
  readonly deckComplete: boolean;
}

export function indexGeneratedMediaReferences(
  document: MediaBearingDocument,
): GeneratedMediaDocumentIndex {
  const materializedOrders = new Set<number>();
  const pendingPlaceholders = new Set<string>();

  const visit = (slide: SlideLike) => {
    for (const slot of slideMediaReferenceSlots(slide)) {
      const ref = slot.read();
      if (ref && isGeneratedMediaPlaceholder(ref)) pendingPlaceholders.add(ref);
    }
  };

  for (const slide of document.stage?.whiteboard ?? []) visit(slide);
  for (const scene of document.scenes ?? []) {
    materializedOrders.add(scene.order);
    for (const slide of slidesOfScene(scene)) visit(slide);
  }

  return {
    materializedOrders,
    pendingPlaceholders,
    deckComplete: document.generationComplete === true,
  };
}

/**
 * Has this generation request already produced durable media?
 *
 * The document is the authority, so the answer is read off it rather than off
 * this browser's task table: the slide that owns the request no longer holds
 * the placeholder, which means either the reference was rewritten to an
 * allocated id or the element was deleted. Both mean "do not call the
 * provider".
 *
 * The absence of a placeholder is decisive only once the slide that would carry
 * it exists, because during a first pass media runs alongside content and the
 * slide may not have been built yet. "Exists" is asked the way the rest of the
 * app asks it — by scene order, the only link between an outline and its scene
 * that the document carries. That link is weaker than it looks: Pro-mode
 * insert and delete rebalance `order`, so on a deck that is still generating,
 * an outline whose scene was renumbered can look unmaterialized and be
 * generated again. A finished deck is exempt: every outline that still has a
 * scene has one, so the placeholder's absence answers on its own and the
 * renumbering cannot cause a needless call.
 */
export function isGeneratedMediaSatisfied(
  index: GeneratedMediaDocumentIndex,
  outlineOrder: number,
  placeholderRef: string,
): boolean {
  if (index.pendingPlaceholders.has(placeholderRef)) return false;
  return index.deckComplete || index.materializedOrders.has(outlineOrder);
}
